/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __TINNED_H__
#define __TINNED_H__
#ifdef __cplusplus
extern "C" {
#endif

/** \brief
 *  An *opaque* handle that C can only pass around
 */
typedef struct ExprHandle ExprHandle_t;


#include <stddef.h>
#include <stdint.h>

/** \brief
 *  `&'lt [T]` but with a guaranteed `#[repr(C)]` layout.
 *
 *  # C layout (for some given type T)
 *
 *  ```c
 *  typedef struct {
 *  // Cannot be NULL
 *  T * ptr;
 *  size_t len;
 *  } slice_T;
 *  ```
 *
 *  # Nullable pointer?
 *
 *  If you want to support the above typedef, but where the `ptr` field is
 *  allowed to be `NULL` (with the contents of `len` then being undefined)
 *  use the `Option< slice_ptr<_> >` type.
 */
typedef struct slice_ref_ExprHandle_const_ptr {
    /** \brief
     *  Pointer to the first element (if any).
     */
    ExprHandle_t const * const * ptr;

    /** \brief
     *  Element count
     */
    size_t len;
} slice_ref_ExprHandle_const_ptr_t;

/** \brief
 *  An *opaque* handle that C can only pass around
 */
typedef struct TinnedErrorHandle TinnedErrorHandle_t;

/** <No documentation available> */
ExprHandle_t *
tinned_add_new (
    slice_ref_ExprHandle_const_ptr_t terms,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_add_term_at (
    ExprHandle_t const * h,
    size_t i,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
size_t
tinned_add_terms_count (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_adjoint_map_generator_at (
    ExprHandle_t const * h,
    size_t i,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
size_t
tinned_adjoint_map_generators_count (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);


#include <stdbool.h>

/** <No documentation available> */
bool
tinned_adjoint_map_left_action (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_adjoint_map_new (
    slice_ref_ExprHandle_const_ptr_t generators,
    ExprHandle_t const * target,
    bool left_action,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_adjoint_map_target (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_composition_inner (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
char *
tinned_composition_name (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_composition_new (
    char const * name,
    uint32_t order,
    ExprHandle_t const * inner,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
uint32_t
tinned_composition_order (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_conjugate_argument (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_conjugate_new (
    ExprHandle_t const * argument,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
bool
tinned_dot_product_allow_braket_swap (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_dot_product_bra (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_dot_product_conjugate (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_dot_product_ket (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_dot_product_new (
    ExprHandle_t const * bra,
    bool use_hermitian,
    ExprHandle_t const * ket,
    bool allow_braket_swap,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
char *
tinned_error_display (
    TinnedErrorHandle_t const * err);

/** <No documentation available> */
void
tinned_error_free (
    TinnedErrorHandle_t * err);

/** <No documentation available> */
ExprHandle_t *
tinned_expr_clone (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_expr_deserialize_json (
    char const * json,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
char *
tinned_expr_display (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
void
tinned_expr_free (
    ExprHandle_t * expr);

/** <No documentation available> */
char *
tinned_expr_hash_key (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
bool
tinned_expr_is_scalar (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
char *
tinned_expr_serialize_json (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
typedef struct NumberToleranceHandle NumberToleranceHandle_t;

/** <No documentation available> */
NumberToleranceHandle_t *
tinned_get_global_number_tolerance (void);

/** <No documentation available> */
double
tinned_number_tolerance_abs_error (
    NumberToleranceHandle_t const * h);

/** <No documentation available> */
void
tinned_number_tolerance_free (
    NumberToleranceHandle_t * tol);

/** <No documentation available> */
NumberToleranceHandle_t *
tinned_number_tolerance_new (
    double abs_error,
    double rel_error);

/** <No documentation available> */
double
tinned_number_tolerance_rel_error (
    NumberToleranceHandle_t const * h);

/** <No documentation available> */
NumberToleranceHandle_t *
tinned_number_tolerance_zero (void);

/** \brief
 *  An *opaque* handle that C can only pass around
 */
typedef struct PertMultichainHandle PertMultichainHandle_t;

/** \brief
 *  An *opaque* handle that C can only pass around
 */
typedef struct PerturbationHandle PerturbationHandle_t;

/** <No documentation available> */
PertMultichainHandle_t *
tinned_pert_multichain_add (
    PertMultichainHandle_t const * h,
    PerturbationHandle_t const * p,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
PertMultichainHandle_t *
tinned_pert_multichain_clone (
    PertMultichainHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
char *
tinned_pert_multichain_display (
    PertMultichainHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
void
tinned_pert_multichain_free (
    PertMultichainHandle_t * chain);

/** \brief
 *  `&'lt [T]` but with a guaranteed `#[repr(C)]` layout.
 *
 *  # C layout (for some given type T)
 *
 *  ```c
 *  typedef struct {
 *  // Cannot be NULL
 *  T * ptr;
 *  size_t len;
 *  } slice_T;
 *  ```
 *
 *  # Nullable pointer?
 *
 *  If you want to support the above typedef, but where the `ptr` field is
 *  allowed to be `NULL` (with the contents of `len` then being undefined)
 *  use the `Option< slice_ptr<_> >` type.
 */
typedef struct slice_ref_PerturbationHandle_const_ptr {
    /** \brief
     *  Pointer to the first element (if any).
     */
    PerturbationHandle_t const * const * ptr;

    /** \brief
     *  Element count
     */
    size_t len;
} slice_ref_PerturbationHandle_const_ptr_t;

/** <No documentation available> */
PertMultichainHandle_t *
tinned_pert_multichain_from_slice (
    slice_ref_PerturbationHandle_const_ptr_t perturbations,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
uint32_t
tinned_pert_multichain_get_order (
    PertMultichainHandle_t const * h,
    PerturbationHandle_t const * p,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
bool
tinned_pert_multichain_has_overlap (
    PertMultichainHandle_t const * lhs,
    PertMultichainHandle_t const * rhs,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
bool
tinned_pert_multichain_insert (
    PertMultichainHandle_t * h,
    PerturbationHandle_t const * p,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
bool
tinned_pert_multichain_is_empty (
    PertMultichainHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
bool
tinned_pert_multichain_is_subchain (
    PertMultichainHandle_t const * lhs,
    PertMultichainHandle_t const * rhs,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
bool
tinned_pert_multichain_is_superchain (
    PertMultichainHandle_t const * lhs,
    PertMultichainHandle_t const * rhs,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
PertMultichainHandle_t *
tinned_pert_multichain_new (void);

/** <No documentation available> */
uint32_t
tinned_pert_multichain_total_order (
    PertMultichainHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
PerturbationHandle_t *
tinned_perturbation_clone (
    PerturbationHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
char *
tinned_perturbation_display (
    PerturbationHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
void
tinned_perturbation_free (
    PerturbationHandle_t * pert);

/** <No documentation available> */
ExprHandle_t *
tinned_perturbation_frequency (
    PerturbationHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
char *
tinned_perturbation_name (
    PerturbationHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
PerturbationHandle_t *
tinned_perturbation_new (
    char const * name,
    ExprHandle_t const * frequency,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
void
tinned_set_global_number_tolerance (
    NumberToleranceHandle_t const * h);

/** <No documentation available> */
void
tinned_string_free (
    char * s);

/** \brief
 *  Get the `name` of a `Symbol`.
 *  - Returns a newly allocated C string; free with `tinned_string_free`.
 */
char *
tinned_symbol_name (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** \brief
 *  Create a new `Symbol` expression.
 *  - `name`: UTF-8 C string (nullable). On NULL/invalid, sets `out_err` and returns `None`.
 *  - Returns an `ExprBox` on success.
 */
ExprHandle_t *
tinned_symbol_new (
    char const * name,
    TinnedErrorHandle_t * * out_err);


#ifdef __cplusplus
} /* extern \"C\" */
#endif

#endif /* __TINNED_H__ */
