/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __TINNED_H__
#define __TINNED_H__
#ifdef __cplusplus
extern "C" {
#endif

/** \brief
 *  An *opaque* handle that C can only pass around
 */
typedef struct ExprHandle ExprHandle_t;


#include <stddef.h>
#include <stdint.h>

/** \brief
 *  Borrowed slice of handles
 */
typedef struct ExprSlice {
    /** <No documentation available> */
    ExprHandle_t const * const * ptr;

    /** <No documentation available> */
    size_t len;
} ExprSlice_t;

/** \brief
 *  An *opaque* handle that C can only pass around
 */
typedef struct TinnedErrorHandle TinnedErrorHandle_t;

/** <No documentation available> */
ExprHandle_t *
tinned_add_new (
    ExprSlice_t const * terms,
    TinnedErrorHandle_t * * out_err);

/** \brief
 *  Same as [`Vec<T>`][`rust::Vec`], but with guaranteed `#[repr(C)]` layout
 */
typedef struct Vec_ExprHandle_ptr {
    /** <No documentation available> */
    ExprHandle_t * * ptr;

    /** <No documentation available> */
    size_t len;

    /** <No documentation available> */
    size_t cap;
} Vec_ExprHandle_ptr_t;

/** <No documentation available> */
Vec_ExprHandle_ptr_t
tinned_add_terms (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
/** \remark Has the same ABI as `uint32_t` **/
#ifdef DOXYGEN
typedef
#endif
enum AdjointMode {
    /** <No documentation available> */
    ADJOINT_MODE_COMMUTATIVE,
    /** <No documentation available> */
    ADJOINT_MODE_SYMMETRIZED,
    /** <No documentation available> */
    ADJOINT_MODE_ORDERED,
}
#ifndef DOXYGEN
; typedef uint32_t
#endif
AdjointMode_t;

/** <No documentation available> */
AdjointMode_t
tinned_adjoint_map_adjoint_mode (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
Vec_ExprHandle_ptr_t
tinned_adjoint_map_generators (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);


#include <stdbool.h>

/** <No documentation available> */
bool
tinned_adjoint_map_left_action (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_adjoint_map_new (
    ExprSlice_t const * generators,
    ExprHandle_t const * target,
    bool left_action,
    AdjointMode_t adjoint_mode,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_adjoint_map_target (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
bool
tinned_ao_two_elec_energy_allow_density_swap (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** \brief
 *  An *opaque* handle that C can only pass around
 */
typedef struct PertMultichainHandle PertMultichainHandle_t;

/** <No documentation available> */
PertMultichainHandle_t *
tinned_ao_two_elec_energy_dependencies (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
PertMultichainHandle_t *
tinned_ao_two_elec_energy_derivative (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_ao_two_elec_energy_inner_density (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
char *
tinned_ao_two_elec_energy_name (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_ao_two_elec_energy_new (
    char const * name,
    ExprHandle_t const * inner_density,
    ExprHandle_t const * outer_density,
    bool allow_density_swap,
    PertMultichainHandle_t const * dependencies,
    PertMultichainHandle_t const * derivative,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_ao_two_elec_energy_outer_density (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_ao_two_elec_matrix_density (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
PertMultichainHandle_t *
tinned_ao_two_elec_matrix_dependencies (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
PertMultichainHandle_t *
tinned_ao_two_elec_matrix_derivative (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
char *
tinned_ao_two_elec_matrix_name (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_ao_two_elec_matrix_new (
    char const * name,
    ExprHandle_t const * density,
    PertMultichainHandle_t const * dependencies,
    PertMultichainHandle_t const * derivative,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
bool
tinned_basis_time_evolution_at_zero_perturbations (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_basis_time_evolution_braket (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
PertMultichainHandle_t *
tinned_basis_time_evolution_dependencies (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
PertMultichainHandle_t *
tinned_basis_time_evolution_derivative (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_basis_time_evolution_new (
    PertMultichainHandle_t const * dependencies,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_composition_inner (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
char *
tinned_composition_name (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_composition_new (
    char const * name,
    uint32_t order,
    ExprHandle_t const * inner,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
uint32_t
tinned_composition_order (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_conjugate_argument (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_conjugate_new (
    ExprHandle_t const * argument,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
bool
tinned_dot_product_allow_braket_swap (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_dot_product_bra (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_dot_product_conjugate (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_dot_product_ket (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_dot_product_new (
    ExprHandle_t const * bra,
    bool use_hermitian,
    ExprHandle_t const * ket,
    bool allow_braket_swap,
    bool is_scalar,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
char *
tinned_error_display (
    TinnedErrorHandle_t const * err);

/** <No documentation available> */
void
tinned_error_free (
    TinnedErrorHandle_t * err);

/** <No documentation available> */
ExprHandle_t *
tinned_exch_corr_energy_density_matrix (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
PertMultichainHandle_t *
tinned_exch_corr_energy_derivative (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_exch_corr_energy_grid_weight (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
char *
tinned_exch_corr_energy_name (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_exch_corr_energy_new (
    char const * name,
    ExprHandle_t const * grid_weight,
    ExprHandle_t const * density_matrix,
    ExprHandle_t const * overlap_distribution,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_exch_corr_energy_overlap_distribution (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_exch_corr_energy_xc_energy (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_exch_corr_potential_density_matrix (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
PertMultichainHandle_t *
tinned_exch_corr_potential_derivative (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_exch_corr_potential_grid_weight (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
char *
tinned_exch_corr_potential_name (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_exch_corr_potential_new (
    char const * name,
    ExprHandle_t const * grid_weight,
    ExprHandle_t const * density_matrix,
    ExprHandle_t const * overlap_distribution,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_exch_corr_potential_overlap_distribution (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_exch_corr_potential_xc_potential (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
char *
tinned_excitation_operator_name (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** \brief
 *  Create a new `ExcitationOperator` expression.
 *  - `name`: UTF-8 C string (nullable). On NULL/invalid, sets `out_err` and returns `None`.
 *  - Returns an `ExprBox` on success.
 */
ExprHandle_t *
tinned_excitation_operator_new (
    char const * name,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
PertMultichainHandle_t *
tinned_exp_adjoint_map_derivative (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_exp_adjoint_map_generator (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
bool
tinned_exp_adjoint_map_generator_derivative_commute (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
bool
tinned_exp_adjoint_map_is_time_evolution (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
bool
tinned_exp_adjoint_map_left_action (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
uint32_t
tinned_exp_adjoint_map_max_commutator_order (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_exp_adjoint_map_new (
    ExprHandle_t const * generator,
    bool generator_derivative_commute,
    ExprHandle_t const * target,
    bool left_action,
    uint32_t max_commutator_order,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_exp_adjoint_map_result (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_exp_adjoint_map_target (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_exp_adjoint_map_time_evolution_new (
    ExprHandle_t const * generator,
    bool is_forward,
    bool generator_derivative_commute,
    bool left_action,
    uint32_t max_commutator_order,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_expr_clone (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_expr_deserialize_json (
    char const * json,
    TinnedErrorHandle_t * * out_err);

/** \brief
 *  An *opaque* handle that C can only pass around
 */
typedef struct PerturbationHandle PerturbationHandle_t;

/** <No documentation available> */
ExprHandle_t *
tinned_expr_differentiate (
    ExprHandle_t const * h,
    PerturbationHandle_t const * s,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
char *
tinned_expr_display (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** \brief
 *  Borrowed slice of handles
 */
typedef struct PerturbationSlice {
    /** <No documentation available> */
    PerturbationHandle_t const * const * ptr;

    /** <No documentation available> */
    size_t len;
} PerturbationSlice_t;

/** <No documentation available> */
ExprHandle_t *
tinned_expr_eliminate (
    ExprHandle_t const * h,
    ExprHandle_t const * parameter,
    PerturbationSlice_t const * perturbations,
    uint32_t min_order,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
bool
tinned_expr_eq (
    ExprHandle_t const * lhs,
    ExprHandle_t const * rhs,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
typedef struct ExprSuperchainHandle ExprSuperchainHandle_t;

/** <No documentation available> */
ExprSuperchainHandle_t *
tinned_expr_find_all (
    ExprHandle_t const * h,
    ExprHandle_t const * s,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
void
tinned_expr_free (
    ExprHandle_t * expr);

/** <No documentation available> */
bool
tinned_expr_has_unperturbed_term (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
char *
tinned_expr_hash_key (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
bool
tinned_expr_is_scalar (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
bool
tinned_expr_match_any (
    ExprHandle_t const * h,
    ExprSlice_t const * set,
    bool include_derivatives,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_expr_remove_all (
    ExprHandle_t const * h,
    ExprSlice_t const * set,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_expr_remove_one (
    ExprHandle_t const * h,
    ExprHandle_t const * s,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_expr_replace_all (
    ExprHandle_t const * h,
    ExprSlice_t const * keys,
    ExprSlice_t const * values,
    bool include_derivatives,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_expr_retain_all (
    ExprHandle_t const * h,
    ExprSlice_t const * set,
    bool include_derivatives,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
char *
tinned_expr_serialize_json (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
typedef struct NumberToleranceHandle NumberToleranceHandle_t;

/** <No documentation available> */
ExprHandle_t *
tinned_expr_substitute_zero_perturbations (
    ExprHandle_t const * h,
    NumberToleranceHandle_t const * tol,
    TinnedErrorHandle_t * * out_err);

/** \brief
 *  Free a superchains object (NULL-safe).
 */
void
tinned_expr_superchains_free (
    ExprSuperchainHandle_t * h);

/** <No documentation available> */
size_t
tinned_expr_superchains_len (
    ExprSuperchainHandle_t const * h);

/** <No documentation available> */
uint32_t
tinned_expr_superchains_order_at (
    ExprSuperchainHandle_t const * h,
    size_t order_idx,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_expr_superchains_order_expr_at (
    ExprSuperchainHandle_t const * h,
    size_t order_idx,
    size_t expr_idx,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
size_t
tinned_expr_superchains_order_len (
    ExprSuperchainHandle_t const * h,
    size_t order_idx);

/** <No documentation available> */
char *
tinned_expr_type_name (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** \brief
 *  Free a vector of `repr_c::Vec<ExprBox>`.
 *  Dropping the Vec drops each ExprBox, which decrements Arc counts.
 */
void
tinned_expr_vec_free (
    Vec_ExprHandle_ptr_t _v);

/** <No documentation available> */
NumberToleranceHandle_t *
tinned_get_global_number_tolerance (void);

/** <No documentation available> */
ExprHandle_t *
tinned_hermitian_transpose_argument (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_hermitian_transpose_new (
    ExprHandle_t const * argument,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
PertMultichainHandle_t *
tinned_lag_multiplier_derivative (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
bool
tinned_lag_multiplier_is_perturbing (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
char *
tinned_lag_multiplier_name (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_lag_multiplier_new (
    char const * name,
    bool is_perturbing,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_matrix_add_new (
    ExprSlice_t const * terms,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
Vec_ExprHandle_ptr_t
tinned_matrix_add_terms (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_matrix_mul_coefficient (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
Vec_ExprHandle_ptr_t
tinned_matrix_mul_factors (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_matrix_mul_new (
    ExprSlice_t const * terms,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_mul_coefficient (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
Vec_ExprHandle_ptr_t
tinned_mul_factors (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_mul_new (
    ExprSlice_t const * terms,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
PertMultichainHandle_t *
tinned_non_elec_function_dependencies (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
PertMultichainHandle_t *
tinned_non_elec_function_derivative (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** \brief
 *  Same as [`Vec<T>`][`rust::Vec`], but with guaranteed `#[repr(C)]` layout
 */
typedef struct Vec_PerturbationHandle_ptr {
    /** <No documentation available> */
    PerturbationHandle_t * * ptr;

    /** <No documentation available> */
    size_t len;

    /** <No documentation available> */
    size_t cap;
} Vec_PerturbationHandle_ptr_t;

/** <No documentation available> */
Vec_PerturbationHandle_ptr_t
tinned_non_elec_function_independent_perturbations (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
bool
tinned_non_elec_function_is_perturbing (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
char *
tinned_non_elec_function_name (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_non_elec_function_new (
    char const * name,
    bool is_perturbing,
    PertMultichainHandle_t const * dependencies,
    PerturbationSlice_t const * independent_perturbations,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_number_conjugate (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
typedef struct CComplex64 {
    /** <No documentation available> */
    double re;

    /** <No documentation available> */
    double im;
} CComplex64_t;

/** <No documentation available> */
ExprHandle_t *
tinned_number_from_complex (
    CComplex64_t z);

/** <No documentation available> */
ExprHandle_t *
tinned_number_from_f64 (
    double f);

/** <No documentation available> */
ExprHandle_t *
tinned_number_from_i64 (
    int64_t n);

/** <No documentation available> */
typedef struct CRational64 {
    /** <No documentation available> */
    int64_t num;

    /** <No documentation available> */
    int64_t den;
} CRational64_t;

/** <No documentation available> */
ExprHandle_t *
tinned_number_from_rational (
    CRational64_t q,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_number_imaginary_unit (void);

/** <No documentation available> */
bool
tinned_number_is_one (
    ExprHandle_t const * h,
    NumberToleranceHandle_t const * tol,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
bool
tinned_number_is_zero (
    ExprHandle_t const * h,
    NumberToleranceHandle_t const * tol,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_number_minus_one (void);

/** <No documentation available> */
ExprHandle_t *
tinned_number_negate (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_number_one (void);

/** <No documentation available> */
ExprHandle_t *
tinned_number_one_half (void);

/** <No documentation available> */
double
tinned_number_tolerance_abs_error (
    NumberToleranceHandle_t const * h);

/** <No documentation available> */
void
tinned_number_tolerance_free (
    NumberToleranceHandle_t * tol);

/** <No documentation available> */
NumberToleranceHandle_t *
tinned_number_tolerance_new (
    double abs_error,
    double rel_error);

/** <No documentation available> */
double
tinned_number_tolerance_rel_error (
    NumberToleranceHandle_t const * h);

/** <No documentation available> */
NumberToleranceHandle_t *
tinned_number_tolerance_zero (void);

/** <No documentation available> */
ExprHandle_t *
tinned_number_zero (void);

/** <No documentation available> */
PertMultichainHandle_t *
tinned_one_elec_matrix_dependencies (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
PertMultichainHandle_t *
tinned_one_elec_matrix_derivative (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
Vec_PerturbationHandle_ptr_t
tinned_one_elec_matrix_independent_perturbations (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
bool
tinned_one_elec_matrix_is_perturbing (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
char *
tinned_one_elec_matrix_name (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_one_elec_matrix_new (
    char const * name,
    bool is_perturbing,
    PertMultichainHandle_t const * dependencies,
    PerturbationSlice_t const * independent_perturbations,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
PertMultichainHandle_t *
tinned_pert_multichain_add (
    PertMultichainHandle_t const * h,
    PerturbationHandle_t const * p,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
PertMultichainHandle_t *
tinned_pert_multichain_clone (
    PertMultichainHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
char *
tinned_pert_multichain_display (
    PertMultichainHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
void
tinned_pert_multichain_free (
    PertMultichainHandle_t * chain);

/** <No documentation available> */
typedef struct PerturbationEntry {
    /** <No documentation available> */
    PerturbationHandle_t * perturbation;

    /** <No documentation available> */
    uint32_t max_order;
} PerturbationEntry_t;

/** \brief
 *  Slice of `PerturbationEntry`
 */
typedef struct PerturbationEntrySlice {
    /** <No documentation available> */
    PerturbationEntry_t const * ptr;

    /** <No documentation available> */
    size_t len;
} PerturbationEntrySlice_t;

/** <No documentation available> */
PertMultichainHandle_t *
tinned_pert_multichain_from_entries (
    PerturbationEntrySlice_t entries,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
PertMultichainHandle_t *
tinned_pert_multichain_from_slice (
    PerturbationSlice_t const * perturbations,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
uint32_t
tinned_pert_multichain_get_order (
    PertMultichainHandle_t const * h,
    PerturbationHandle_t const * p,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
bool
tinned_pert_multichain_has_overlap (
    PertMultichainHandle_t const * lhs,
    PertMultichainHandle_t const * rhs,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
bool
tinned_pert_multichain_insert (
    PertMultichainHandle_t * h,
    PerturbationHandle_t const * p,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
bool
tinned_pert_multichain_is_empty (
    PertMultichainHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
bool
tinned_pert_multichain_is_subchain (
    PertMultichainHandle_t const * lhs,
    PertMultichainHandle_t const * rhs,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
bool
tinned_pert_multichain_is_superchain (
    PertMultichainHandle_t const * lhs,
    PertMultichainHandle_t const * rhs,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
PertMultichainHandle_t *
tinned_pert_multichain_new (void);

/** <No documentation available> */
Vec_PerturbationHandle_ptr_t
tinned_pert_multichain_to_vec (
    PertMultichainHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
uint32_t
tinned_pert_multichain_total_order (
    PertMultichainHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
PerturbationHandle_t *
tinned_perturbation_clone (
    PerturbationHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
char *
tinned_perturbation_display (
    PerturbationHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
PerturbationEntry_t
tinned_perturbation_entry_new (
    PerturbationHandle_t * perturbation,
    uint32_t max_order);

/** \brief
 *  Free a perturbation (NULL-safe).
 */
void
tinned_perturbation_free (
    PerturbationHandle_t * pert);

/** <No documentation available> */
ExprHandle_t *
tinned_perturbation_frequency (
    PerturbationHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
char *
tinned_perturbation_name (
    PerturbationHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
PerturbationHandle_t *
tinned_perturbation_new (
    char const * name,
    ExprHandle_t const * frequency,
    TinnedErrorHandle_t * * out_err);

/** \brief
 *  Frees a vector of perturbation boxes returned by Rust.
 *
 *  This also drops all contained `PerturbationBox` elements.
 *  The caller must not free the elements separately afterward.
 */
void
tinned_perturbation_vec_free (
    Vec_PerturbationHandle_ptr_t _v);

/** <No documentation available> */
ExprHandle_t *
tinned_power_base (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
int64_t
tinned_power_exponent (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_power_new (
    ExprHandle_t const * base,
    int64_t exponent,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_residue_parameter_excited_state (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_residue_parameter_new (
    PerturbationSlice_t const * perturbations,
    ExprHandle_t const * excited_state,
    ExprHandle_t const * parameter,
    bool positive_frequency,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_residue_parameter_parameter (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
Vec_PerturbationHandle_ptr_t
tinned_residue_parameter_perturbations (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
bool
tinned_residue_parameter_positive_frequency (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
void
tinned_set_global_number_tolerance (
    NumberToleranceHandle_t const * h);

/** <No documentation available> */
void
tinned_string_free (
    char * s);

/** <No documentation available> */
char *
tinned_symbol_name (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** \brief
 *  Create a new `Symbol` expression.
 *  - `name`: UTF-8 C string (nullable). On NULL/invalid, sets `out_err` and returns `None`.
 *  - Returns an `ExprBox` on success.
 */
ExprHandle_t *
tinned_symbol_new (
    char const * name,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_time_evolution_argument (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
PertMultichainHandle_t *
tinned_time_evolution_derivative (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_time_evolution_frequency (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
bool
tinned_time_evolution_is_forward (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_time_evolution_new (
    ExprHandle_t const * argument,
    bool is_forward,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_trace_argument (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_trace_new (
    ExprHandle_t const * argument,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_transpose_argument (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_transpose_new (
    ExprHandle_t const * argument,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
PertMultichainHandle_t *
tinned_two_elec_matrix_dependencies (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
PertMultichainHandle_t *
tinned_two_elec_matrix_derivative (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
Vec_PerturbationHandle_ptr_t
tinned_two_elec_matrix_independent_perturbations (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
bool
tinned_two_elec_matrix_is_perturbing (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
char *
tinned_two_elec_matrix_name (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_two_elec_matrix_new (
    char const * name,
    bool is_perturbing,
    PertMultichainHandle_t const * dependencies,
    PerturbationSlice_t const * independent_perturbations,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
/** \remark Has the same ABI as `uint32_t` **/
#ifdef DOXYGEN
typedef
#endif
enum ExprTag {
    /** <No documentation available> */
    EXPR_TAG_ADD,
    /** <No documentation available> */
    EXPR_TAG_ADJOINT_MAP,
    /** <No documentation available> */
    EXPR_TAG_AO_TWO_ELEC_ENERGY,
    /** <No documentation available> */
    EXPR_TAG_AO_TWO_ELEC_MATRIX,
    /** <No documentation available> */
    EXPR_TAG_BASIS_TIME_EVOLUTION,
    /** <No documentation available> */
    EXPR_TAG_COMPOSITION,
    /** <No documentation available> */
    EXPR_TAG_CONJUGATE,
    /** <No documentation available> */
    EXPR_TAG_DOT_PRODUCT,
    /** <No documentation available> */
    EXPR_TAG_EXCH_CORR_ENERGY,
    /** <No documentation available> */
    EXPR_TAG_EXCH_CORR_POTENTIAL,
    /** <No documentation available> */
    EXPR_TAG_EXCITATION_OPERATOR,
    /** <No documentation available> */
    EXPR_TAG_EXP_ADJOINT_MAP,
    /** <No documentation available> */
    EXPR_TAG_HERMITIAN_TRANSPOSE,
    /** <No documentation available> */
    EXPR_TAG_LAG_MULTIPLIER,
    /** <No documentation available> */
    EXPR_TAG_MATRIX_ADD,
    /** <No documentation available> */
    EXPR_TAG_MATRIX_MUL,
    /** <No documentation available> */
    EXPR_TAG_MUL,
    /** <No documentation available> */
    EXPR_TAG_NON_ELEC_FUNCTION,
    /** <No documentation available> */
    EXPR_TAG_NUMBER,
    /** <No documentation available> */
    EXPR_TAG_ONE_ELEC_MATRIX,
    /** <No documentation available> */
    EXPR_TAG_POWER,
    /** <No documentation available> */
    EXPR_TAG_RESIDUE_PARAMETER,
    /** <No documentation available> */
    EXPR_TAG_SUB_EXPR,
    /** <No documentation available> */
    EXPR_TAG_SYMBOL,
    /** <No documentation available> */
    EXPR_TAG_TIME_EVOLUTION,
    /** <No documentation available> */
    EXPR_TAG_TRACE,
    /** <No documentation available> */
    EXPR_TAG_TRANSPOSE,
    /** <No documentation available> */
    EXPR_TAG_TWO_ELEC_MATRIX,
    /** <No documentation available> */
    EXPR_TAG_WFN_PARAMETER,
    /** <No documentation available> */
    EXPR_TAG_ZERO_OPERATOR,
}
#ifndef DOXYGEN
; typedef uint32_t
#endif
ExprTag_t;

/** <No documentation available> */
typedef struct CExprVisitor {
    /** <No documentation available> */
    void * ctx;

    /** <No documentation available> */
    bool (*begin_node)(void *, ExprTag_t, size_t);

    /** <No documentation available> */
    bool (*on_leaf)(void *, ExprTag_t, ExprHandle_t *);

    /** <No documentation available> */
    bool (*end_node)(void *, ExprTag_t, size_t);
} CExprVisitor_t;

/** <No documentation available> */
bool
tinned_walk_expr_postorder (
    ExprHandle_t const * h,
    CExprVisitor_t visitor,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
PertMultichainHandle_t *
tinned_wfn_parameter_derivative (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
bool
tinned_wfn_parameter_is_perturbing (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
char *
tinned_wfn_parameter_name (
    ExprHandle_t const * h,
    TinnedErrorHandle_t * * out_err);

/** <No documentation available> */
ExprHandle_t *
tinned_wfn_parameter_new (
    char const * name,
    bool is_perturbing,
    TinnedErrorHandle_t * * out_err);

/** \brief
 *  Create a new `ZeroOperator` expression.
 */
ExprHandle_t *
tinned_zero_operator_new (void);


#ifdef __cplusplus
} /* extern \"C\" */
#endif

#endif /* __TINNED_H__ */
