#pragma once

/* @generated by cbindgen -- do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

typedef struct ExprBox ExprBox;

typedef struct PertMultichainBox PertMultichainBox;

typedef struct PerturbationBox PerturbationBox;

typedef struct TinnedErrorBox TinnedErrorBox;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

void tinned_free_cstring(char *s);

void tinned_error_free(struct TinnedErrorBox *err);

char *tinned_error_display(const struct TinnedErrorBox *err);

struct ExprBox *tinned_expr_ref(struct ExprBox *h);

void tinned_expr_unref(struct ExprBox *h);

bool tinned_expr_is_scalar(const struct ExprBox *h, struct TinnedErrorBox **out_err);

char *tinned_expr_hash_key(const struct ExprBox *h, struct TinnedErrorBox **out_err);

char *tinned_expr_display(const struct ExprBox *h, struct TinnedErrorBox **out_err);

char *tinned_expr_serialize_json(const struct ExprBox *h, struct TinnedErrorBox **out_err);

struct ExprBox *tinned_expr_deserialize_json(const char *json);

struct ExprBox *tinned_add_new(const struct ExprBox *const *term_ptrs,
                               size_t term_count,
                               struct TinnedErrorBox **out_err);

size_t tinned_add_terms_count(const struct ExprBox *h, struct TinnedErrorBox **out_err);

struct ExprBox *tinned_add_term_at(const struct ExprBox *h,
                                   size_t i,
                                   struct TinnedErrorBox **out_err);

struct ExprBox *tinned_adjoint_map_new(const struct ExprBox *const *generator_ptrs,
                                       size_t generator_count,
                                       const struct ExprBox *target_ptr,
                                       bool left_action,
                                       struct TinnedErrorBox **out_err);

size_t tinned_adjoint_map_generators_count(const struct ExprBox *h,
                                           struct TinnedErrorBox **out_err);

struct ExprBox *tinned_adjoint_map_generator_at(const struct ExprBox *h,
                                                size_t i,
                                                struct TinnedErrorBox **out_err);

struct ExprBox *tinned_adjoint_map_target(const struct ExprBox *h, struct TinnedErrorBox **out_err);

bool tinned_adjoint_map_left_action(const struct ExprBox *h, struct TinnedErrorBox **out_err);

struct ExprBox *tinned_composition_new(const char *name_cstr,
                                       uint32_t order,
                                       const struct ExprBox *inner_ptr,
                                       struct TinnedErrorBox **out_err);

char *tinned_composition_name(const struct ExprBox *h, struct TinnedErrorBox **out_err);

uint32_t tinned_composition_order(const struct ExprBox *h, struct TinnedErrorBox **out_err);

struct ExprBox *tinned_composition_inner(const struct ExprBox *h, struct TinnedErrorBox **out_err);

struct ExprBox *tinned_conjugate_new(const struct ExprBox *argument_ptr,
                                     struct TinnedErrorBox **out_err);

struct ExprBox *tinned_conjugate_argument(const struct ExprBox *h, struct TinnedErrorBox **out_err);

struct ExprBox *tinned_dot_product_new(const struct ExprBox *bra_ptr,
                                       bool use_hermitian,
                                       const struct ExprBox *ket_ptr,
                                       bool allow_braket_swap,
                                       struct TinnedErrorBox **out_err);

struct ExprBox *tinned_dot_product_bra(const struct ExprBox *h, struct TinnedErrorBox **out_err);

struct ExprBox *tinned_dot_product_ket(const struct ExprBox *h, struct TinnedErrorBox **out_err);

bool tinned_dot_product_allow_braket_swap(const struct ExprBox *h, struct TinnedErrorBox **out_err);

struct ExprBox *tinned_dot_product_conjugate(const struct ExprBox *h,
                                             struct TinnedErrorBox **out_err);

struct PertMultichainBox *tinned_pert_multichain_ref(struct PertMultichainBox *h);

void tinned_pert_multichain_unref(struct PertMultichainBox *h);

struct PertMultichainBox *tinned_pert_multichain_new(void);

struct PertMultichainBox *tinned_pert_multichain_from_slice(const struct PerturbationBox *const *perturbation_ptrs,
                                                            size_t perturbation_count,
                                                            struct TinnedErrorBox **out_err);

bool tinned_pert_multichain_insert(struct PertMultichainBox *h,
                                   const struct PerturbationBox *p,
                                   struct TinnedErrorBox **out_err);

uint32_t tinned_pert_multichain_get_order(const struct PertMultichainBox *h,
                                          const struct PerturbationBox *p);

bool tinned_pert_multichain_is_empty(const struct PertMultichainBox *h);

uint32_t tinned_pert_multichain_total_order(const struct PertMultichainBox *h);

bool tinned_pert_multichain_is_subchain(const struct PertMultichainBox *lhs,
                                        const struct PertMultichainBox *rhs);

bool tinned_pert_multichain_is_superchain(const struct PertMultichainBox *lhs,
                                          const struct PertMultichainBox *rhs);

bool tinned_pert_multichain_has_overlap(const struct PertMultichainBox *lhs,
                                        const struct PertMultichainBox *rhs);

char *tinned_pert_multichain_display(const struct PertMultichainBox *h,
                                     struct TinnedErrorBox **out_err);

struct PerturbationBox *tinned_perturbation_ref(struct PerturbationBox *h);

void tinned_perturbation_unref(struct PerturbationBox *h);

struct PerturbationBox *tinned_perturbation_new(const char *name_cstr,
                                                const struct ExprBox *frequency_ptr,
                                                struct TinnedErrorBox **out_err);

char *tinned_perturbation_name(const struct PerturbationBox *h, struct TinnedErrorBox **out_err);

struct ExprBox *tinned_perturbation_frequency(const struct PerturbationBox *h,
                                              struct TinnedErrorBox **out_err);

char *tinned_perturbation_display(const struct PerturbationBox *h, struct TinnedErrorBox **out_err);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
