[package]
name = "tinned_ffi"
version = "0.1.0"
edition = "2024"
include = ["include/**", "src/**", "Cargo.toml"]

[lib]
name = "tinned_ffi"
crate-type = ["rlib", "cdylib", "staticlib"]

[dependencies]
tinned_lib = { path = "../tinned_lib", features = ["ffi"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
safer-ffi = { version = "0.1.13", features = ["proc_macros"] }
paste = "1.0.15"
num-complex = "0.4.6"
num-rational = "0.4.2"

[features]
c-headers = ["safer-ffi/headers"]
